mod 'openstack-ceph', '3.1.1'
mod 'openstack-openstacklib', '17.3.0'
mod 'puppetlabs-apache', '5.5.0'
mod 'puppetlabs-inifile', '4.3.0'
mod 'puppetlabs-stdlib', '6.4.0'
mod 'duritong-sysctl', '0.0.12'
mod 'puppetlabs-concat', '6.2.0'
mod 'puppetlabs-translate', '2.2.0'
